{
 "title": "Service Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Containers UP",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up == 1)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Containers DOWN",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up == 0)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service!=\"\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service!=\"\"}",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Inbound Network Traffic",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{container_label_com_docker_compose_service!=\"\"}[2m])",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Outbound Network Traffic",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{container_label_com_docker_compose_service!=\"\"}[2m])",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Service Reachability",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"container_services\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 } }
 ]
}