global:
  scrape_interval: 15s         # How often to scrape metrics from targets (default 15s)
  evaluation_interval: 15s     # How often to evaluate rules (default 15s)

scrape_configs:
  - job_name: 'prometheus'     # Prometheus self-monitoring
    static_configs:
      - targets: ['localhost:9090']

  # Example node_exporter scrape config
  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: ['node-exporter-hostname:9100']
  